# Generated by Django 5.1.5 on 2025-08-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='lvl',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Úroveň'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='xp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Zkušenosti'),
        ),
    ]
