# Generated by Django 5.1.5 on 2025-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='charisma_plus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='plus k charismatu'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='dexterity_plus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='plus k obratnosti'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='intelligence_plus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='plus k inteligenci'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='luck_plus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='plus k zručnosti'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='strength_plus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='plus k síle'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='vitality_plus',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='plus k vitalitě'),
        ),
    ]
