# Generated by Django 5.1.5 on 2025-08-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='orders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena'), ('other', 'Jiné')], max_length=10, null=True),
        ),
    ]
