# Generated by Django 5.1.5 on 2025-08-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0002_playerinfo_charisma_plus_playerinfo_dexterity_plus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinfo',
            old_name='charisma',
            new_name='suma_charisma',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='dexterity',
            new_name='suma_dexterity',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='intelligence',
            new_name='suma_intelligence',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='luck',
            new_name='suma_luck',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='strength',
            new_name='suma_strength',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='vitality',
            new_name='suma_vitality',
        ),
    ]
