# Generated by Django 5.1.5 on 2025-08-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0002_customuser_orders_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='orders',
            field=models.IntegerField(blank=True, null=True, verbose_name='Počet objednávek'),
        ),
    ]
