# Generated by Django 5.1.5 on 2025-08-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0002_remove_customuser_nickname_remove_customuser_pozn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gold',
            field=models.IntegerField(default=0, verbose_name='Počet GOLDŮ'),
        ),
    ]
