# Generated by Django 5.1.5 on 2025-08-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0003_customuser_nickname_alter_customuser_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Emailová adresa'),
        ),
    ]
