# Generated by Django 5.1.5 on 2025-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0003_playerinfo_frakce_playerinfo_povolani_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerinfo',
            name='frakce',
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='povolani',
            field=models.CharField(blank=True, choices=[('HUNTER', 'Bojovník'), ('PRIEST', 'Kněz'), ('WARRIOR', 'Válečník'), ('PALADIN', 'Paladin'), ('MAGE', 'Mág'), ('ROGUE', 'Roguna'), ('NECROMANCER', 'Nekromant'), ('BERSERKER', 'Ničitel'), ('WARLOCK', 'Temný mág'), ('DRUID', 'Druid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='rasa',
            field=models.CharField(blank=True, choices=[('human', 'Člověk'), ('elf', 'Elf'), ('dwarf', 'Trpaslík'), ('Urgal', 'Urgal'), ('Gnóm', 'Gnóm'), ('Dark Elf', 'Temný Elf')], max_length=20, null=True),
        ),
    ]
