# Generated by Django 5.1.5 on 2025-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0003_customuser_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rohlik',
            field=models.IntegerField(default=1, verbose_name='Počet ROHLÍKŮ'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gold',
            field=models.IntegerField(default=1, verbose_name='Počet GOLDŮ'),
        ),
    ]
