# Generated by Django 5.1.5 on 2025-08-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0004_customuser_rohlik_alter_customuser_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gold_grow',
            field=models.IntegerField(default=1, verbose_name='Růst GOLDŮ za 1s'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_gold_collection',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
