# Generated by Django 5.1.5 on 2025-08-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0004_remove_playerinfo_frakce_alter_playerinfo_povolani_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('Choice:', 'Vyber:'), ('male', 'Muž'), ('female', 'Žena'), ('other', 'Jiné')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='povolani',
            field=models.CharField(blank=True, choices=[('Choice:', 'Vyber:'), ('HUNTER', 'Bojovník'), ('PRIEST', 'Kněz'), ('WARRIOR', 'Válečník'), ('PALADIN', 'Paladin'), ('MAGE', 'Mág'), ('ROGUE', 'Roguna'), ('NECROMANCER', 'Nekromant'), ('BERSERKER', 'Ničitel'), ('WARLOCK', 'Temný mág'), ('DRUID', 'Druid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='rasa',
            field=models.CharField(blank=True, choices=[('Choice:', 'Vyber:'), ('human', 'Člověk'), ('elf', 'Elf'), ('dwarf', 'Trpaslík'), ('Urgal', 'Urgal'), ('Gnóm', 'Gnóm'), ('Dark Elf', 'Temný Elf')], max_length=20, null=True),
        ),
    ]
