# Generated by Django 5.1.5 on 2025-08-26 09:30

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0005_customuser_gold_grow_customuser_last_gold_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_gold_collection',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now, null=True),
        ),
    ]
