# Generated by Django 5.1.5 on 2025-08-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pozn',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
    ]
