# Generated by Django 5.1.5 on 2025-08-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0005_alter_playerinfo_gender_alter_playerinfo_povolani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='HP_bonus',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='Bonus k životům'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='charisma_base',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Základní charisma'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='dexterity_base',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Základní obratnost'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='intelligence_base',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Základní inteligence'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='skill_base',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Základní zručnost'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='strength_base',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Základní síla'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='vitality_base',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Základní vitalita'),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena'), ('other', 'Jiné')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='rasa',
            field=models.CharField(blank=True, choices=[('Choice:', 'Vyber:'), ('human', 'Člověk'), ('elf', 'Elf'), ('dwarf', 'Trpaslík'), ('Urgal', 'Urgal'), ('Gnóm', 'Gnóm'), ('Shadow', 'Stín')], max_length=20, null=True),
        ),
    ]
