# Generated by Django 5.1.5 on 2025-08-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0006_alter_customuser_last_gold_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gold_growth_coefficient',
            field=models.FloatField(default=1.0, verbose_name='Koeficient růstu GOLDŮ'),
        ),
    ]
