# Generated by Django 5.1.5 on 2025-08-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0007_customuser_gold_growth_coefficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gold_grow',
        ),
    ]
