# Generated by Django 5.1.5 on 2025-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0008_remove_customuser_gold_grow'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='HP',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Počet životů'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='charisma',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Charisma'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dexterity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Obratnost'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='intelligence',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Inteligence'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skill',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Zručnost'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='strength',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Síla'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vitality',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Vitalita'),
        ),
    ]
