# Generated by Django 5.1.5 on 2025-08-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0009_customuser_hp_customuser_charisma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='orders',
            new_name='steps',
        ),
    ]
