# Generated by Django 5.1.5 on 2025-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0002_playerinfo_lvl_playerinfo_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='frakce',
            field=models.CharField(blank=True, choices=[('Light Side', 'Světlo'), ('Dark Side', 'Prázdnota')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='povolani',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='rasa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
