# Generated by Django 5.1.5 on 2025-08-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hracapp', '0006_playerinfo_hp_bonus_playerinfo_charisma_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinfo',
            old_name='HP_bonus',
            new_name='hp_bonus',
        ),
    ]
