# Generated by Django 5.1.5 on 2025-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_init', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(choices=[('none', 'Žádná'), ('heavy', 'Těžké'), ('light', 'Lehké'), ('magic', 'Magické')], default='none', max_length=10)),
                ('damage', models.IntegerField(default=1)),
                ('level_required', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
