# Generated by Django 5.1.5 on 2025-08-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='level_stop',
            field=models.IntegerField(default=10),
        ),
    ]
