# Generated by Django 5.1.5 on 2025-08-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0002_weapons_level_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapons',
            name='damage',
        ),
    ]
